server:
  port: 5000
spring:  application:    name: welisit-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:    host: 127.0.0.1
  session:    store-type: redis
  profiles:
    active:
    - dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka